CREATE OR REPLACE CONTEXT USER_CTX USING set_user_ctx_pkg;
/

CREATE OR REPLACE PACKAGE set_user_ctx_pkg IS 
  PROCEDURE set_user;
END;
/

CREATE OR REPLACE PACKAGE BODY set_user_ctx_pkg IS
  PROCEDURE set_user IS
    myRole VARCHAR2(255);
  BEGIN 
    SELECT GRANTED_ROLE INTO myRole
    FROM DBA_ROLE_PRIVS
    WHERE GRANTEE = SYS_CONTEXT('USERENV','SESSION_USER')
    AND GRANTED_ROLE LIKE 'ADMIN18%';
    DBMS_SESSION.SET_CONTEXT('USER_CTX','role',myRole);
    DBMS_SESSION.SET_CONTEXT('USER_CTX','idUser',SYS_CONTEXT('USERENV','SESSION_USER'));
  END set_user;
END set_user_ctx_pkg;
/

GRANT EXECUTE ON set_user_ctx_pkg TO USER1;
GRANT EXECUTE ON set_user_ctx_pkg TO USER2;
GRANT EXECUTE ON set_user_ctx_pkg TO USER3;
GRANT EXECUTE ON set_user_ctx_pkg TO USER4;
GRANT EXECUTE ON set_user_ctx_pkg TO USER5;
GRANT EXECUTE ON set_user_ctx_pkg TO USER6;
GRANT EXECUTE ON set_user_ctx_pkg TO USER7;
